### ISSUE TITLE
log in details

### ISSUE THREAD

**Issue by raymondfx** [ScanTrust/sawtooth-explorer#70]
Just managed to set up and run this explorer, but it has log in page, what log in details should i use, or am I missing something here.
<img width="823" alt="Screenshot 2019-12-18 07 54 30" src="https://user-images.githubusercontent.com/26685061/71056820-a879e700-216b-11ea-9a30-1dd27c254d46.png">

**Comment by bormisov1** [comment]
@raymondfx my bad, forgot to make registration public by default, just fixed by #71
Thanks for using this!

**Comment by bormisov1** [comment]
to specify explored node's addresses use REST_API_URL and VALIDATOR_URL envs with values in this format: ```'http://localhost:8043'
'tcp://localhost:4040'```
